repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: check-builtin-literals
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: trailing-whitespace
