[tool.isort]
line_length = 88
force_grid_wrap = 0

multi_line_output = 3
include_trailing_comma = true
use_parentheses = true

# No import comments, thanks.
import_heading_future = ""
import_heading_stdlib = ""
import_heading_thirdparty = ""
import_heading_firstparty = ""
import_heading_localfolder = ""
